const languageSettings = 
{
english: {    
    languageText: "ENGLISH",        
    textChoose: "Choose your language!",
    welcomeTextRed: "Work through JobFIXers",
    welcomeTextMore: "and earn more!",
    welcomeTextGray: "Phasellus sed tellus quis justo finibus tempus. Nam sagittis sollicitudin turpis.",
    buttonText: "I want to earn more!",
    buttonNextText: "Next one",
    buttonTextJob: "I want a job!",
    firstNameText: "First Name",
    lastNameText: "Name",
    telephoneNumberText: "Telephone Number",
    FNameErrorText: "First Name is not Valid",
    LNameErrorText: "Last Name is not Valid",
    TelephoneNumberError: "Telephone Number is not valid",
    EmptyErrorText: "All Fields are Required!",
    CheckBoxErrorText: "Check Box is Required!",
    workText: "I want to work if:",
    postalCodeText: "Postalcode",
    policyText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Suspendisse sit amet erat amet nulla consequat rutrum.",
    thankYouText: "Thanks!",
    thankYouTextOne: "We will call you as soon",
    thankYouTextTwo: "as possible",
    followText: "follow us on",
    industry: "Worker",
    construct: "Construction Worker",
    office: "Clerk"
},

dutch: {    
    languageText: "NEDERLANDS",
    welcomeTextRed: "Werk via JobFIXers",
    welcomeTextMore: "en verdien meer!",
    welcomeTextGray: "Phasellus sed tellus quis justo finibus tempus. Nam sagittis sollicitudin turpis.",
    buttonText: "Ik wil meer verdienen!",
    buttonNextText: "VOLGENDE",
    firstNameText: "Voornaam",
    lastNameText: "Naam",
    telephoneNumberText: "Telefoonnummer",
    FNameErrorText: "First Name is not Valid",
    LNameErrorText: "Last Name is not Valid",
    TelephoneNumberError: "Telephone Number is not valid",
    EmptyErrorText: "Alle velden zijn verplicht!",
    CheckBoxErrorText: "Selectievakje is verplicht!",
    workText: "Ik wil werken als:",
    postalCodeText: "Postcode",
    policyText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Suspendisse sit amet erat amet nulla consequat rutrum.",
    buttonTextJob: "Ik wil een job!",
    thankYouText: "Bedankt!",
    thankYouTextOne: "We Bellen jou zo snel",
    thankYouTextTwo: "mogelijk op!",
    followText: "Volg ons op",
    industry: "Arbeider",
    construct: "Bouwvakker",
    office: "Bediende"
},

french: {    
    languageText: "FRANÇAIS",
    welcomeTextRed: "Travaillez via JobFIXers",
    welcomeTextMore: "et gagnez plus!",
    welcomeTextGray: "Phasellus sed tellus quis justo finibus tempus. Nam sagittis sollicitudin turpis.",
    buttonText: "Je veux gagner plus!",
    buttonNextText: "SUIVANTE",
    buttonTextJob: "Je veux un travail!",
    firstNameText: "Prénom",
    lastNameText: "Nom",
    telephoneNumberText: "Numéro de téléphone",
    FNameErrorText: "First Name is not Valid",
    LNameErrorText: "Last Name is not Valid",
    TelephoneNumberError: "Telephone Number is not valid",
    EmptyErrorText: "Tous les champs sont requis!",
    CheckBoxErrorText: "La case à cocher est obligatoire!",
    nextText: "Next one",
    workText: "Je veux travailler si:",
    postalCodeText: "Code postal",
    policyText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Suspendisse sit amet erat amet nulla consequat rutrum.",
    thankYouText: "Merci! Nous vous appellerons dès que possible!",
    thankYouTextOne: "Nous vous appellerons dès que",
    thankYouTextTwo: "possible!",
    followText: "Suivez nous",
    industry: "Travailleur",
    construct: "Travailleur de construction",
    office: "Employé"
}
};

export default languageSettings;